name: inception

services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes: 
      - mariadb_data:/var/lib/mysql
    env_file: .env
    networks: 
      - inception

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    env_file: .env
    networks: 
      - inception
    depends_on: 
      - mariadb #preciser le statut de mariadb





volumes:

  mariadb_data:
    driver: local
#    driver_opts:
#      type: none
#      device: ${VOLUMES_DIR}mariadb
#      o: bind
  
  wordpress_data:
    driver: local
#    driver_opts:
#      type: none
#      device: ${VOLUMES_DIR}wordpress
#      o: bind

networks:
  inception:
    driver: bridge
